version: 2

jobs:
  test:
    docker:
      - image: circleci/python:3.6.5
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Setup Python virtual environment
          command: |
            python3 -m venv venv
            echo "source $(pwd)/venv/bin/activate" >> $BASH_ENV
      - run: pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run: python3 -m pytest .

workflows:
  version: 2
  pytest:
    jobs:
      - test
